### ISSUE TITLE
Is it possible to return hostname instead of IP?

### ISSUE THREAD

**Issue by peterdalydickson** [snoopdouglas/ansible-inventory-doctl-tags#2]
This script is brilliant! And I didn't know about doctl either. Thanks for both.

Quick question.. is it possible to return hostname in the JSON string, instead of IP? I attempted a few things to make that work but I'm no programmer really!

Thanks again.

**Comment by snoopdouglas** [comment]
Haha thanks! :) currently this isn't something it can do - but adding this as an option should be easy.

We'll use another environment variable for this - probably `DOCTL_INVENTORY_OUTPUT_HOSTNAMES`.

**Comment by snoopdouglas** [comment]
Turns out finding the actual droplet *hostname* (rather than its 'name' on DigitalOcean) is a lot more tough. The vast majority of the time, these values are identical though - so this should be enough for what you need @peterdalydickson.

To correspond with this, the environment variable you'll need to have set has changed to simply `DOCTL_INVENTORY_OUTPUT_NAMES` (`HOST` has been removed).

**Comment by peterdalydickson** [comment]
This'll work perfectly for me!

Thanks @snoopdouglas
